title: Leipziger Initiative gegen Islamismus
description: Leipziger Initiative gegen Islamismus

url: https://gegen-islamismus.de
baseurl: ""
permalink: blog/:title/

markdown: kramdown

navigation:
 - title: Aufruf
   url: /index.html
 - title: Kundgebung
   url: /kundgebung
 - title: Kontakt
   url: /kontakt

social:
   github:
   twitter:
   facebook:
   email: gegen.islamismus@protonmail.com

google_analytics:
