title: Leipziger Initiative gegen Islamismus
description: Leipziger Initiative gegen Islamismus

url: https://gegen-islamismus.de
baseurl: ""
permalink: blog/:title/

markdown: kramdown

navigation:
 - title: Aufruf
   url: /index.html
 - title: Kontakt
   url: /kontakt
 - title: Facebook
   url: https://www.facebook.com/Leipziger-Initiative-gegen-Islamismus-2191724911109853

social:
   github:
   twitter:
   facebook:
   email:

google_analytics:
